# Azure DevOps Pipeline for dev, test, and prod environments
pool:
stages:


trigger:
	- main

pool:
	name: Default

jobs:
	- job: echo_job
		displayName: 'Echo Job'
		steps:
			- script: echo "Pipeline triggered by GitHub push."
				displayName: 'Echo step'
