name: Publish Azure DevOps Extension

on:
  push:
    branches:
      - main

jobs:
  publish-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install tfx-cli
        run: npm install -g tfx-cli

      - name: Package extension
        run: tfx extension create --manifest-globs vss-extension.json

      - name: Publish extension
        run: tfx extension publish --manifest-globs vss-extension.json --token ${{ secrets.AZURE_DEVOPS_PAT }}
